- github-backup.py
> #1 Remove references to backup directory

- .project
> #1 Prepare for version

- github-util.py
> Issue 5.dockter.1

- CHANGELOG.md
> #5 Prepare for versioned release

- github-util.py
- requirements.txt
> Issue 8.dockter.1

- CHANGELOG.md
- github-util.py
- requirements.txt
> Issue 15.dockter.1

- github-util.py
- update-base-dockerfiles-example.json
- update-dockerfiles-example.json
> Issue 17.dockter.2

- update-base-dockerfiles-example.json
- update-dockerfiles-example.json
> #21 updated Debian and Alpine images

- update-base-dockerfiles-example.json
- update-dockerfiles-example.json
> #23 updated date

- update-base-dockerfiles-example.json
- update-dockerfiles-example.json
> Issue 23.ron.0

- update-dockerfiles-example.json
> #27 Update base images

- github-util.py
> #29 Added is_user

- CONTRIBUTING.md
- examples/add-to-project/add-to-project.sh
- examples/add-triage-label/add-triage-label.sh
- examples/identify-customer/identify-customer.sh
- github-util.py
- update-base-dockerfiles-example.json
- update-dockerfiles-example.json
> #31 Update base docker versions

- update-base-dockerfiles-example.json
- update-dockerfiles-example.json
> #33 updated base images

- .github/workflows/pylint.yaml
- .pylintrc
- CHANGELOG.md
- github-util.py
> Issue 35.dockter.1

- github-util.py
> #41 Add print-repository-names-with-pages subcommand

- .pylintrc
- github-util.py
> #43 Add --with-archived to print-repository-names

- update-dockerfiles-example.json
> #45 Add metadata for entity-search-web-app

- update-dockerfiles-example.json
> #47 added comma where needed

- update-base-dockerfiles-example.json
- update-dockerfiles-example.json
> #57 update base images

- update-dockerfiles-step-3-example.json
> #59 Add entity-search-web-app-console

- update-dockerfiles-step-1-example.json
- update-dockerfiles-step-2-example.json
- update-dockerfiles-step-3-example.json
> Issue 59.dockter.3

- update-dockerfiles-step-2-example.json
- update-dockerfiles-step-3-example.json
> #59 Update senzing versions

- update-dockerfiles-step-3-example.json
> Issue 59.dockter.5

- update-dockerfiles-step-1-example.json
- update-dockerfiles-step-2-example.json
- update-dockerfiles-step-3-example.json
> Issue 65.dockter.1

- update-dockerfiles-step-3-example.json
> #65 Add init-mysql

- update-dockerfiles-step-3-example.json
> #65 Update images

- update-dockerfiles-step-1-example.json
- update-dockerfiles-step-2-example.json
- update-dockerfiles-step-3-example.json
> #65 Update versions

- update-dockerfiles-step-3-example.json
> #65 Update risk-score-calculator

- update-dockerfiles-step-1-example.json
- update-dockerfiles-step-2-example.json
- update-dockerfiles-step-3-example.json
> Issue 73.dockter.1

- github-util.py
> #75 filter out 'master'

- github-util.py
> #79 Savepoint

- update-dockerfiles-step-1-example.json
- update-dockerfiles-step-2-example.json
- update-dockerfiles-step-3-example.json
> Issue 87.dockter.1

- update-dockerfiles-step-1-example.json
- update-dockerfiles-step-2-example.json
- update-dockerfiles-step-3-example.json
> 93.dockter.1

- .github/workflows/lint-repo.yaml
- examples/add-to-project/README.md
- examples/repository-teams/README.md
Issue number: senzing-factory/build-resources#106
> senzing-factory/build-resources#106 cleanup topics

- update-dockerfiles-step-1-example.json
- update-dockerfiles-step-2-example.json
> #108 Update base images

- update-dockerfiles-step-2-example.json
- update-dockerfiles-step-3-example.json
> #110 update base images and remove deprecated repo

- .github/workflows/add-to-project-factory.yaml
Issue number: senzing-factory/build-resources#124
> senzing-factory/build-resources#124 reuse add to project and update permissions

- .github/workflows/lint-repo.yaml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
Issue number: senzing-factory/build-resources#144
> senzing-factory/build-resources#144 cleanup

- update-dockerfiles-step-1-example.json
- update-dockerfiles-step-2-example.json
- update-dockerfiles-step-3-example.json
> #121 3.10.1 updates

- update-dockerfiles-step-1-example.json
> #109 remove old base images

- update-dockerfiles-step-1-example.json
- update-dockerfiles-step-2-example.json
- update-dockerfiles-step-3-example.json
> 3.10.3 updates

- github-util.py
- requirements.txt
- update-dockerfiles-step-1-example.json
- update-dockerfiles-step-2-example.json
- update-dockerfiles-step-3-example.json
> #95 support signed commits
